### ISSUE TITLE
Query.addParameterInternal throws "java.langNullPointerException: null"

### ISSUE THREAD

**Issue by 4rnstein** [aaberg/sql2o#151] opened 2014-09-22 06:59 UTC
Problem:
With complex query, its hard to know whats wrong.
private void addParameterInternal(String name, ParameterSetter parameterSetter) {
        for (int paramIdx : this.getParamNameToIdxMap().get(name)) {
            try {
                parameterSetter.setParameter(paramIdx);
            } catch (SQLException e) {
                throw new RuntimeException(String.format("Error adding parameter '%s' - %s", name, e.getMessage()), e);
            }
        }
    }

Example: Add a parameter that dosent exist in sql  statement
        final String sql = "UPDATE db.Muppet SET name = :name WHERE id = :id";
 db.createQuery(sql)
.addParameter("name", name)
.addParameter("age",age) 
.addParameter("id", id) .executeUpdate();

Solution
Check if this.getParamNameToIdxMap().get(name) is null and then throw
throw new RuntimeException(String.format("Error adding parameter '%s' - Missing parameter", name));

**Comment by aaberg** [comment] 2015-01-21 22:56
Duplicate of #149.

**Closed by aaberg** 2015-01-21 22:56 UTC
Labels: bug, duplicate, priority-normal
