### ISSUE TITLE
NPE on Query.addParameter when parameter is not present in query

### ISSUE THREAD

**Issue by klaushauschild1984** [aaberg/sql2o#187] opened 2015-06-01 21:18 UTC
This problem occurs in sql2o-1.5.4.

connection.createQuery("SELECT * FROM TABLE").addParameter("someparameter", 123);
This snippet results in a NPE because "someparameter" is not present at the current query.
Do not throw a NPE or give some hint through the error message what's wrong.

Thanks

**Comment by aaberg** [comment] 2015-08-10 07:22
Closing. This is a duplicate of #149

**Closed by aaberg** 2015-08-10 07:22 UTC
Labels: bug
