### ISSUE TITLE
Put a list parameter to query IN condition.

### ISSUE THREAD

**Issue by vinhxike** [aaberg/sql2o#178] opened 2015-02-26 02:26 UTC
I don't know the way to build query has IN condition. I tried http://screencast.com/t/Hlacb0h7rDWh. Could you please show me how can i do it?

**Comment by vinhxike** [comment] 2015-02-26 02:45
I also change c.status IN (:status) and use query.addParameter("status", "\"ONLINE\", \"COMPLETED\"") or query.addParameter("status", "'ONLINE', 'COMPLETED'") but it don't work.

**Comment by aaberg** [comment] 2015-03-01 15:26
Duplicate of #146

**Closed by aaberg** 2015-03-01 15:26 UTC
Labels: duplicate
