### ISSUE TITLE
Bug in Query.bind() method when execute batch queries

### ISSUE THREAD

**Issue by miroslavivanov1988** [aaberg/sql2o#192] opened 2015-07-20 15:12 UTC
I use Query.bind() in batch execution. If I try to insert N records it will bind the values from first entity and insert N numbers of exactly the same rows.

For example:

public void insertABunchOfRows(List<Entity> entities){
    final String sql = "INSERT INTO SomeTable(value1, value2) VALUES (:value1, :value2)";

    try (Connection con = sql2o.beginTransaction()) {
        Query query = con.createQuery(sql);

        for (Entity entity : entities){
            query.bind(entity)
                    .addToBatch();
        }

        query.executeBatch();
        con.commit();         
    }
}

The list "entities" contains:
new Entitiy(1, 2);
new Entitiy(3, 4);
new Entitiy(5, 6);
...
N

The database table looks like:

Value1 Value2
1          2
1          2
1          2
...
N

**Comment by pavanjaju** [comment] 2015-07-31 19:53
+1
Any update on this issue?

**Comment by aaberg** [comment] 2015-08-01 08:10
I have labeled it as a high priority bug

**Comment by zsoca8711** [comment] 2015-08-01 12:56
When can you look at this?
I'm thinking to resolve this bug to support you and this wonderful library :) I'm not sure about it, i'm with two kids, but if you say it may take weeks to resolve, i'm happy to play with it in one of the evenings.

**Comment by zsoca8711** [comment] 2015-08-01 19:31
Haha, this is funny, because i've forked your code to fix it, added a unittest to cover the issue and the unittest ran fine.
I think the explanation is this: https://github.com/aaberg/sql2o/issues/177 :) 
I've raised this issue before and you fixed it.

Shall i setup a pull request for the unittest?

**Comment by aaberg** [comment] 2015-08-02 10:19
Ahh, I thought the problem sounded familiar :)

Yes, please make a pull request with the unittest, I will gladly accept it!

**Comment by aaberg** [comment] 2015-08-10 13:57
Closed as duplicate of #177

**Closed by aaberg** 2015-08-10 13:57 UTC
Labels: bug, priority-high
