### ISSUE TITLE
Connection leak reported by HikariCP for try-with-resources

### ISSUE THREAD

**Issue by sachin-walia** [aaberg/sql2o#232] opened 2016-05-31 18:46 UTC
We have microservices built using Spring Boot and I use sql2o at repository layer. We are using HikariCP as pooling library and I've noticed that after few days HikariCP is not able to borrow connection from pool. It turns out that all connections are exhausted. After enabling leakConnectionThreshold settings in HikariCP it was reported that following construct is not releasing connection. I am attaching a sample class that shows what we are doing since I may not be able to attach the actual code.

Hikari reports that leakage is happening at:

`
try (Connection con = sql2o.open()) {
`

Our Environment:
1. Spring Boot 1.3.3
2. Spring 4.2.5
3. Sql2o 1.5.4
4. Java 8
5. HikariCP - 2.4.5
6. Mysql 5.5

Also - we don't use Any Quirks setting for Mysql.

**For now I am moving classes away from try with resources to see if this seems to be the problem. However any insight into this will be helpful.**

Complete sample class. All our repository classes follow the same pattern. we use try with resources to ensure connection closing.

```
package somepackage;

import java.util.List;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.sql2o.Connection;
import org.sql2o.Query;
import org.sql2o.Sql2o;

@Repository(value = "someRepository")
public class SomeRepositoryImpl implements SomeRepository {

    @Autowired
    private Sql2o sql2o;
    private final Logger LOGGER = LoggerFactory.getLogger(getClass());

    @Override
    public void deleteSomething() {
        String sql = "Some SQL Query";
        try (Connection conn = sql2o.open()) {
            conn.createQuery(sql)
                    .executeUpdate();
        }
    }
}
```

**Comment by aaberg** [comment] 2016-06-03 07:27
This is very stange! Have you been able to reproduce the leak in a test/development environment?

In your `deleteSomething()` method, you use the `conn` object to execute the query, but connection variable is called `con`. I assume this is just a typo when creating the example class?

**Comment by sachinwalia2k8** [comment] 2016-06-03 16:21
@aaberg It is not reproducible always but whenever it is reported it is always reported on this lines. FYI it has been reported in multiple different repository classes but doesn't happen all the time. Also I've updated the variable name to "conn". that was a typo.

For what it's worth I used JMeter to send 100s of thread to the controller that invokes this code and I couldn't reproduce this issue. Interestingly enough it only starts happening after few days - 5 to 7 days.

**Comment by aaberg** [comment] 2016-06-06 06:37
Do you get any exceptions or warnings in your logs from sql2o when this is happening?

**Comment by dimzon** [comment] 2016-06-06 12:57
2016-06-03 19:21 GMT+03:00 Sachin Walia <notifications@github.com>:

> It is not reproducible always but whenever it is reported it is always
> reported on this lines. FYI it has been reported in multiple different
> repository classes but doesn't happen all the time.


Seem's like racing conditions... Try to reproduce running as multiple
threads as possible...

**Comment by sachinwalia2k8** [comment] 2016-06-16 00:54
This got printed today again. I was using Jboss connection pool previously but Hikari is known to be very efficient at catching leaks so these errors were never produced before. However what is happening that after a weak or so we run out of all connections in the pool. 

FYI - sql2o is 1.5.4

**Exception trace:**
```
[2016-06-15 20:53:10,941] [WARN] [Hikari housekeeper (pool appPool)] Connection leak detection triggered for connection com.mysql.jdbc.JDBC4Connection@15e94098, stack trace follows
java.lang.Exception: Apparent connection leak detected
        at org.sql2o.Connection.createConnection(Connection.java:288)
        at org.sql2o.Connection.<init>(Connection.java:51)
        at org.sql2o.Sql2o.open(Sql2o.java:225)
... (more application stack trace)
```

**line #288 as mentioned in the log below if following code:**

`            this.jdbcConnection = this.sql2o.getDataSource().getConnection();
`

**I am manually opening and closing sql2o Connection in the code. Something like below:**

```
	public Table executeQuery() {
		String query = "select query...";
		Connection conn = null;
		try {
			conn = sql2o.open();
			return conn.createQuery(query).setAutoDeriveColumnNames(true).executeAndFetchTable();
		} catch(SQLException e){
			//error log
		} finally {
			if(conn != null){
				conn.close();
			}
		}
		return null;
	}

```

**Comment by aaberg** [comment] 2016-06-16 20:34
Thanks for the information. I will let you know if I figure out what is causing this. Meanwhile, please let me know if you find any reliable way to reproduce the leak.

**Comment by sachinwalia2k8** [comment] 2016-06-16 20:45
sure. will update this issue as soon as I get more info.

**Comment by aaberg** [comment] 2016-08-14 10:46
I experienced a similar problem some days ago. We had a connection leak, even though the sql2o code was enclosed in a try-with-resource block.

After a lot of debugging, I found out that the problem was caused by static variables in a model class... Of some obscure reason, one of our models looked something like this:

``` java
class MyPojo {
    public static int property1;
    public static String property2;
}
```

This caused a connection leak. The `close()` method was called as expected, but the underlying JDBC connection was not closed when its `close()` method was called, it instead threw an SqlException with message: "Unable to close Connection". Since the application is a multithreaded web application, my guess is that the static variables somehow locked the connection, as it was accessed by multiple threads.

**Comment by rookie7799** [comment] 2017-12-03 21:01
Hi, we are having the same exact issue.

**Comment by gaoquanbing-ausxin** [comment] 2017-12-15 04:50
We also have the same issue, connection leak:

2017-12-15 11:31:03 WARN  ~ Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@5e7cc6c7 on thread http-nio-8080-exec-325, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.hibernate.service.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:141)
	at org.hibernate.internal.AbstractSessionImpl$NonContextualJdbcConnectionAccess.obtainConnection(AbstractSessionImpl.java:301)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.obtainConnection(LogicalConnectionImpl.java:214)
	at org.hibernate.engine.jdbc.internal.LogicalConnectionImpl.getConnection(LogicalConnectionImpl.java:157)
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doBegin(JdbcTransaction.java:67)
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:160)
	at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1387)
	at org.hibernate.ejb.TransactionImpl.begin(TransactionImpl.java:59)
	at play.db.jpa.JPA.withTransaction(JPA.java:249)
	at play.db.jpa.JPA.withinFilter(JPA.java:212)
	at play.db.jpa.JPAPlugin$TransactionalFilter.withinFilter(JPAPlugin.java:292)
	at play.Invoker$Invocation.withinFilter(Invoker.java:281)
	at play.Invoker$Invocation.run(Invoker.java:298)
	at play.server.ServletWrapper$ServletInvocation.run(ServletWrapper.java:559)
	at play.Invoker.invokeInThread(Invoker.java:70)
	at play.server.ServletWrapper.service(ServletWrapper.java:147)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by aaberg** [comment] 2017-12-15 07:02
If you have any more information, that can help identify the source of the leak, it would be highly appreciated.

**Comment by psybox** [comment] 2018-02-09 15:32
Same problem here.

**Comment by crysan** [comment] 2018-11-24 01:30
Same problem here.

**Comment by mariooooo** [comment] 2019-02-26 06:29
Same problem here. When i use sql query with **IN**
```
@Query("select c from Contact c where c.id in :ids")
List<Contact> findByContactsIds(@Param("ids") List<Integer> contactsIds);
```

**Comment by wert1y** [comment] 2019-03-18 18:38
maybe cause of a connection leak i'm experiencing, too. will try to generate a small test case. another detail that might be significant: it seems to be exacerbated by connection failures.

**Comment by VikChauhan20** [comment] 2024-07-02 10:14
Facing somewhat similar issue where few select statements executed leaks connections in try with resource but code works for update and delete statements which too are in try with resource. 
We are using postgresql DB - spring.datasource.driver-class-name=org.postgresql.Driver

Need help

**Comment by weeklynote** [comment] 2024-07-02 10:14
已收到，我会尽快回复你！
                     ——刘劲字

**Comment by aaberg** [comment] 2024-07-04 05:57
@VikChauhan20, can you show us the code that generates the leak?

**Comment by VikChauhan20** [comment] 2024-07-05 11:35
**@aaberg** ... PFA the code snippet.. few values changed for security purposes

    public static Map<String, List<String>> getDetailPopUp(){
        Map<String, List<String>> popUpMap = new HashMap<String, List<String>>();
        String queryString = "select * from TABLE_MITRO_POPUP_DETAILS";
        try (Connection con = dataSource.getConnection(); PreparedStatement pr = con.prepareStatement(queryString)) {
            try (ResultSet rs = pr.executeQuery()) {
                while (rs.next()) {
                    String keyRoleFields = "";
                    String keyRoleValues = "";
                    keyRoleFields = rs.getString("KEY_ROLE_FIELD");
                    keyRoleValues = rs.getString("KEY_ROLE_VALUE");
                    String[] splittedValue = keyRoleValues.split("##");
                    List<String> splittedValues = new ArrayList<String>(Arrays.asList(splittedValue));
                    popUpMap.put(keyRoleFields, splittedValues);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return popUpMap;
    }


**Hikari Properties being used:**
spring.datasource.hikari.minimumIdle=10
spring.datasource.hikari.maximumPoolSize=50
spring.datasource.hikari.idleTimeout=10000
spring.datasource.hikari.connectionTimeout=240000
spring.datasource.hikari.maxLifetime=300000


**Error Screenshot** -- Query in image is different but issue is same
<img width="482" alt="image" src="https://github.com/aaberg/sql2o/assets/174434121/acb7f972-9870-4224-99c4-5334384f6b9f">

**Comment by aaberg** [comment] 2024-07-11 06:31
@VikChauhan20, sorry for the late reply. To me, it looks like you've done everything correctly. It doesn't seem like you are using Sql2o, though, which this thread is about. If anything, my guess is that the issue is with Hikari. I suggest checking out their [github page](https://github.com/brettwooldridge/HikariCP) and asking in their forum :)

**Closed by aaberg** 2024-07-11 06:31 UTC
