### ISSUE TITLE
NullPointerException thrown when parameter not found

### ISSUE THREAD

**Issue by ForgeSeven** [aaberg/sql2o#179] opened 2015-03-02 11:52 UTC
When a parameter does not exist inside a query, a NullPointerException is thrown, with little information. It would be nice if a "ParameterNotFound: paramName" or similar was produced for debugging purposes.

    public static void main(String[] args) {
        MysqlDataSource dataSource = new MysqlDataSource();
        dataSource.setUser("cc");
        dataSource.setPassword("password");

        Sql2o sql2o = new Sql2o(dataSource);

        try (Connection con = sql2o.open()) {
            con.createQuery("select * from table where field = :someParam")
               .addParameter("doesntExist", 40);

        }
    }

Produces:

`Exception in thread "main" java.lang.NullPointerException
	at org.sql2o.Query.addParameterInternal(Query.java:120)
	at org.sql2o.Query.addParameter(Query.java:198)
	at Sql2oTest.main(Sql2oTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)`

Thanks!

P.S. Great framework - we're using it exclusively at my place of work.

**Comment by ForgeSeven** [comment] 2015-03-02 12:01
Just noticed that this has been addressed in your 1.6.0-SNAPSHOT. Will you be releasing 1.5.5 maintenance that this could be included in?

**Comment by aaberg** [comment] 2015-03-03 12:46
Hi, 
there are no plans for any more maintenance releases. This will have to wait until the 1.6.0 release. Hopefully we will be ready with the 1.6.0 release soon.

**Comment by aaberg** [comment] 2015-03-03 12:47
duplicate of #149

**Closed by aaberg** 2015-03-03 12:47 UTC
Labels: duplicate

**Comment by borisfa** [comment] 2015-08-26 07:43
And why just to throw user friendly exception some like "this parameter doesn't exist, 
please correct your spelling " . Many times you don't recognize space or double letters 
or j instead g, so null pointer exception is luck of information about error.
