### ISSUE TITLE
Ignore "org.sql2o.Sql2oException: Could not map xxx to any property"

### ISSUE THREAD

**Issue by natinusala** [aaberg/sql2o#164] opened 2015-01-03 19:38 UTC
Hello,

It would be nice to be able to ignore this exception, because there might be data we don't want to get from the database. For example if we need to fetch an Account using a where clause on its password, we don't need to get it back to the Java object.

Thanks !

**Comment by aaberg** [comment] 2015-01-04 18:09
This is a duplicate of #134

**Closed by aaberg** 2015-01-04 18:09 UTC
Labels: duplicate
