### ISSUE TITLE
No suitable driver found for...

### ISSUE THREAD

**Issue by Lumos-Nox** [aaberg/sql2o#294] opened 2018-03-21 14:00 UTC
Hi,
I'm using tomcat and sql2o to develop web application, but sql2o could not load mysql-connector-java-5.1.23-bin.jar in $CATALINA_HOME/lib, only when this jar file was placed in /Library/Java/Extensions/ directory did it work. Besides, using java native library to require a data source also works. Thanks in advance.

**Comment by klaushauschild1984** [comment] 2018-03-21 15:17
Such problems will mostly not caused by the applications and its libraries. In most cases it is a problem at the setup.
So please double and tripple check your setup. Maybe you can provide more details.

**Comment by Lumos-Nox** [comment] 2018-03-23 15:27
@klaushauschild1984 Thanks for your comment. Let me make it clearer....

#### Brief preview of my project
The setup of the project needs the following JAR files:
- sql2o-1.5.4.jar
- mysql-connector-java-5.1.23-bin.jar
- HikariCP-2.7.8.jar
- slf4j-api-1.7.25.jar
- ...

#### The first case (Success):
```
If I put all JAR files mentioned above in /Library/Java/Extensions, then compile and
build the project, and restart tomcat and run the web application, everything works
fine.
```

#### The second case (Success):
```
If I keep mysql-connector-java-5.1.23-bin.jar in /Library/Java/Extensions, but other
JAR files are moved to $CATALINA_HOME/lib, and repeat the above steps in the first
case, everything works fine again!
```

#### The third case (Failed):
````
If I do the same thing in the second case except that the
mysql-connector-java-5.1.23-bin.jar is moved to $CATALINA_HOME/lib, an error
(500 - Internal Server Error) happens. [Root Cause is: java.sql.SQLException:
No suitable driver].
````

#### The fourth case (Success):
````
I have developed a web application using servlet but import java.sql.* rather than
org.sql2o.*, also mysql-connector-java-5.1.23-bin.jar is moved to $CATALINA_HOME/lib,
but this time the web application works correctly as it should do.
````

I have explained the setup thoroughly, now it is your turn. :-)
Thanks again.
dofadore

**Comment by zapodot** [comment] 2018-03-27 05:52
@Lumos-Nox I do understand that you have an issue, but it has to do with Tomcat and how third-party libraries are added to it. Please consult the Tomcat Classloading guide at https://tomcat.apache.org/tomcat-9.0-doc/class-loader-howto.html
Having said that, adding libraries to the system Java runtime is generally considered to be a bad idea as it makes your application less portable. Usually, database drivers are provided by the application server (i.e Tomcat) or bundled with your application (for instance in the WEB-INF/lib folder of a WAR file). Closing this issue now

**Closed by zapodot** 2018-03-27 05:52 UTC
